<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<div class="form col-md-6 offset-md-3">
  <h2 class = "mt-3 text-center"> Cadastro de Hotel </h2>
  <form id="formCadastrar" class="mt-3">
    <div class="row">
      <div class="form-group col-md-6">
        <label for="nomeHotel">Nome do hotel</label>
        <input required type="text" class="form-control" id="nomeHotel" placeholder="Nome do hotel" name="nomeHotel">
      </div>

      <div class="form-group col-md-6">
        <label for="CNPJ">CNPJ</label>
        <input required type="text" class="form-control" id="CNPJ" placeholder="CNPJ" name="cnpj">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="telefone">Tel. Fixo</label>
        <input required type="text" class="form-control" id="telefone" placeholder="Telefone Fixo" name="telefone">
      </div>

      <div class="form-group col-md-6">
        <label for="rua">Rua</label>
        <input required type="text" class="form-control" id="rua" placeholder="rua" name="rua">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="numero">Número</label>
        <input required type="text" class="form-control" id="numero" placeholder="Número" name="numero">
      </div>

      <div class="form-group col-md-6">
        <label for="bairro">Bairro</label>
        <input required type="text" class="form-control" id="bairro" placeholder="Bairro" name="bairro">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="cidade">Cidade</label>
        <input required type="text" class="form-control" id="cidade" placeholder="Cidade" name="cidade">
      </div>

      <div class="form-group col-md-6">
        <label for="estado">Estado</label>
        <input required type="text" class="form-control" id="estado" placeholder="Estado" name="estado">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="pais">País</label>
        <input required type="text" class="form-control" id="pais" placeholder="País" name="pais">
      </div>

      <div class="form-group col-md-6">
        <label for="cep">CEP</label>
        <input required type="text" class="form-control" id="cep" placeholder="CEP" name="cep">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="email">E-mail</label>
        <input required type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="E-mail" name="email">
      </div>

      <div class="form-group col-md-6 ">
        <label for="senha">Senha</label>
        <input required type="password" class="form-control" id="senha" placeholder="Senha" name="senha">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-12">
        <label for="descricao">Descreva o Hotel</label>
        <textarea required type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição do hotel" rows="5"></textarea>
      </div>
    </div>

    <div class="row">
      <div class= "form-group col-md-12">
        <label for="exampleInputEmail1">Adicione até 3 Imagens</label>
        <input class="form-control" id="imagem1" name="imagem1" type="file" accept="image/*" />
        <input class="form-control" id="imagem2" name="imagem2" type="file" accept="image/*" />
        <input class="form-control" id="imagem3" name="imagem3" type="file" accept="image/*" />
      </div>
    </div>

    <div class="row">
      <div class="row col-md-6 offset-md-3">
        <button  class="btn btn-outline-secondary mr-5">
          <a href="/" >Cancelar</a>
        </button>
        <button id="btnSalvar" type="submit" class="btn btn-outline-info float-right mr-5">Salvar</button>
      </div>
    </div>
  </form>
</div>

<script type="text/javascript">
$('#formCadastrar').submit(function (event) {

  event.preventDefault();

  var dadosHotel = new FormData($(this)[0]);
  
  $('#btnSalvar').prop("disabled", true);
  $('#btnSalvar').html(
  `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>`
  );

  $.ajax({
    type: 'POST',
    enctype: 'multipart/form-data',
    url: '/cadastrarHotel',
    data: dadosHotel,
    processData: false,
    contentType: false,
    cache: false,
    success: function (data) {
      var obj = JSON.parse(data);

      if (obj.status == 'ok') {
          alert("Hotel cadastrado com sucesso!");
          $(location).attr('href', '/');
      }
      else {
          alert(obj.mensagem);
          $('#btnSalvar').prop("disabled", false);
          $('#btnSalvar').html('Salvar');
      }
    },
    error: function (event) {
      console.log(event);
      $('#btnSalvar').prop("disabled", false);
      $('#btnSalvar').html('Salvar');
    }
  });
});
</script>