<?php
extract($this->view->dados);

$entrada = $_REQUEST['entrada'] ? $_REQUEST['entrada'] : '';
$saida = $_REQUEST['saida'] ? $_REQUEST['saida'] : '';

?>

<div class="card mb-3 col-md-8 hotel pt-3 mt-5">
    <div class="bd-example">
        <?php

        if (!$imagem1 && !$imagem2 && !$imagem3) {
        ?>
        <div class="carousel-item active ml-2 d-flex justify-content-center">
            <h3>O Hotel não possui fotos!</h3>
        </div>
        <?php
        } else {

        ?>
        <div id="carouselExampleCaptions" class="carousel carousel-fade slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <?php
            if (isset($imagem1) && $imagem1 != "") {
            ?>
            <div class="carousel-item active">
                <img src="/storage/<?=$id;?>/<?=$imagem1;?>" class="d-block w-100 imagem-hotel">
            </div>
            <?php
            }
            if (isset($imagem2) && $imagem2 != "") {
            ?>
            <div class="carousel-item">
                <img src="/storage/<?=$id;?>/<?=$imagem2;?>" class="d-block imagem-hotel">
            </div>
            <?php
            }
            if (isset($imagem3) && $imagem3 != "") {
            ?>
            <div class="carousel-item">
                <img src="/storage/<?=$id;?>/<?=$imagem3;?>" class="d-block imagem-hotel">
            </div>
            <?php
            }
            ?>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <?php
        }
        ?>
    </div>

    <div class="card-body">
        <div class="row">
            <h4 class="card-title font-weight-bold"><?= $nomeHotel; ?></h4>
            <p class="card-text font-weight-bold ml-3"><?= $descricao; ?></p>
        </div>
        <div class="row mt-5">
            <div class="col-md-5 offset-md-2">
                <p class="card-text font-weight-bold ml-3">Rua: <?= $rua; ?>, <?= $numero; ?></p>
                <p class="card-text font-weight-bold ml-3">Bairro: <?= $bairro; ?></p>
                <p class="card-text font-weight-bold ml-3">Cidade: <?= $cidade; ?> / <?= $estado; ?></p>
                <p class="card-text font-weight-bold ml-3">Email: <?= $email; ?></p>
                <p class="card-text font-weight-bold ml-3">Tel: <?= $telefone; ?></p>
            </div>
            <div class="col-md-4">
                <?php
                if ($entrada != '') {
                ?>
                <p class="card-text font-weight-bold ml-3">
                    Entrada: <?= date('d/m/Y', strtotime($entrada)); ?>
                </p>
                <p class="card-text font-weight-bold ml-3">
                    Saida: <?= date('d/m/Y', strtotime($saida)); ?>
                </p>
                <?php
                }
                else {
                ?>
                <p class="card-text font-weight-bold ml-3">
                    Entrada: Não informada
                </p>
                <p class="card-text font-weight-bold ml-3">
                    Saida: Não informada
                </p>
                <?php
                }
                ?>
            </div>
        </div>
    </div>
    <div>
        <p class="card-text mb-3 text-white-50 bg-secondary">Obs: Ao clicar em Solicitar Reserva um email será enviado ao dono do hotel com sua solicitação
        de reserva, aguarde a resposta do hotel no seu email ou telefone!</p>
    </div>
    <?php
    if (isset($_SESSION['clienteId'])) {
    ?>
    <button id="solicitarReserva" class="btn btn-primary" type="button">
        Solcitar reserva!
    </button>
    <?php
    }
    else {
    ?>
    <button class="btn btn-outline-primary shadow" type="button">
        <a href="/loginCliente">Faça login para continuar</a>
    </button>
    <?php
    }
    ?>
</div>

<script type="text/javascript">
    
$('#solicitarReserva').click(function (event) {
    var dataSent = {
        hotel: <?=json_encode($this->view->dados);?>,
        entrada: "<?= $entrada; ?>",
        saida: "<?= $saida; ?>"
    };

    $(this).prop("disabled", true);
    $(this).html(
    `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Solcitando reserva...`
    );

    $.post("/reservarHotel", dataSent, function( data ) {
        console.log("reservarHotel");
        console.log(data);

        if (JSON.parse(data).status == 'ok') {
            alert("Um e-mail foi encaminhado ao hotel com a solicitação de reserva.\nAguarde o contato do hotel.");

            $(location).attr('href', '/');
        }
        else {
            alert("Não foi possível completar a sua reserva!\nPor favor, tente novamente.");
            $('#solicitarReserva').prop("disabled", false);
            $('#solicitarReserva').html('Solcitar reserva!');
        }
    });
});

</script>