<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="form col-md-6 offset-md-3" style="top: 25% !important;">
  <h2 class="text-center mt-3"> Login do Hotel </h2>
  <form id="formLogin" class="mt-3">
    <div class="row">
      <div class="form-group col-md-6">
        <label for="email">E-mail</label>
        <input required type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="E-mail">
      </div>
      <div class="form-group col-md-6">
        <label for="senha">Senha</label>
        <input required type="password" class="form-control" id="senha" placeholder="Senha">
      </div>
    </div>
    <div class="row ">
      <div class="offset-4 mb-5 mt-2">
        <button class="btn btn-outline-secondary"><a href="/" >Cancelar</a></button>
        <button id="btnEntrar" type="submit" class="btn btn-outline-info ml-4">Entrar</button>
      </div>
    </div>
  </form>
</div>

<script type="text/javascript">
  $('#formLogin').submit(function (event) {

    event.preventDefault();

    var credential = {
      email: $('#email').val(),
      senha: $('#senha').val()
    };

    console.log(credential);

    $('#btnEntrar').prop("disabled", true);
    $('#btnEntrar').html(
    `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>`
    );

    $.post('/loginHotel', credential, function (data) {
      console.log(data);
      if (JSON.parse(data).status == 'ok') {
          $(location).attr('href', '/');
      }
      else {
          alert(JSON.parse(data).mensagem);
          $('#btnEntrar').prop("disabled", false);
          $('#btnEntrar').html('Entrar');
      }
    });
  });
</script>