<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h1 class="titulo">Sr. Hotel</h1>

<form class="div-input form-inline mt-3" method="POST" action="/buscarHoteis">

    <input type="text" class="form-control mr-sm-2" id="cidade" name="cidade"
      placeholder="Cidade (Ex: Fortaleza)" value="<?=$_POST['cidade'];?>"/>
    
    <input type="date" class="form-control mr-sm-2" id="entrada" name="entrada" value="<?=$_POST['entrada'];?>" />
  
    <input type="date" class="form-control mr-sm-2" id="saida" name="saida" value="<?=$_POST['saida'];?>" />
  
    <button class="btn btn-primary" type="submit">Buscar</button>
</form>

<div class="row ml-5 mr-5">
<?php
if (empty($this->view->dados)) {
?>
    <h1 class="offset-md-3 mt-5 mb-5">Nenhum hotel foi encontrado!</h1>
<?php
}
else {
    foreach($this->view->dados as $indice => $hotel) {
    ?>

    <div class="card mt-3 col-md-4 hoteis shadow-lg p-4 mb-5  ">
        <?php
        if($hotel['imagem1']) {
            ?>
            <img src="/storage/<?= $hotel['id']; ?>/<?= $hotel['imagem1']; ?>" class="card-img-top"/>
            <?php
        }else {
            ?>
            <h3 class="ml-4 mr-4 pt-3">O Hotel não possui foto!</h3>
            <?php
        }
            ?>
        <div class="card-body">
            <h4 class="card-title"><?=$hotel['nomeHotel'];?></h4>
            <p class="card-text"> Email: <?=$hotel['email'];?></p>
            <p class="card-text"> Tel: <?=$hotel['telefone'];?> </p>
            <p class="card-text"> Endereco: <?=$hotel['rua'];?>, <?=$hotel['numero'];?> - <?=$hotel['bairro'];?></p>
            <p class="card-text"> Cidade: <?=$hotel['cidade'];?>/<?=$hotel['estado'];?></p>
        </div>
        <a class="btn btn-outline-primary mb-3 shadow" href="/detalharHotel?id=<?=$hotel['id'];?>&entrada=<?=$_POST['entrada'];?>&saida=<?=$_POST['saida'];?>">Detalhar hotel!</a>
    </div>
    <?php
    }
}
?>

</div>
