<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="form col-md-6 offset-md-3">
  <h2 class="mt-2 text-center"> Cadastro Cliente</h2>
  <form id="formCadastrar" class="mt-3">
    <div class="row">
      <div class="form-group col-md-6">
        <label for="nome">Nome Completo</label>
        <input required type="text" class="form-control " id="nome" placeholder="Nome Completo">
      </div>

      <div class="form-group col-md-6">
        <label for="cpf">CPF</label>
        <input required type="text" class="form-control" id="cpf" placeholder="CPF">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="celular">Celular</label>
        <input required type="text" class="form-control" id="celular" placeholder="Celular">
      </div>

      <div class="form-group col-md-6">
        <label for="telefone">Tel. Fixo</label>
        <input type="text" class="form-control" id="telefone" placeholder="Telefone Fixo">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="dt_nascimento">Data de Nascimento</label>
        <input required type="date" class="form-control" id="dt_nascimento" placeholder="Data de Nascimento">
      </div>

      <div class="form-group col-md-6">
        <label for="logradouro">Logradouro</label>
        <input type="text" class="form-control" id="logradouro" placeholder="Logradouro">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="numero">Número</label>
        <input type="text" class="form-control" id="numero" placeholder="Número">
      </div>

      <div class="form-group col-md-6">
        <label for="bairro">Bairro</label>
        <input type="text" class="form-control" id="bairro" placeholder="Bairro">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="complemento">Complemento</label>
        <input type="text" class="form-control" id="complemento" placeholder="Complemento">
      </div>

      <div class="form-group col-md-6">
        <label for="cep">CEP</label>
        <input type="text" class="form-control" id="cep" placeholder="CEP">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="cidade">Cidade</label>
        <input type="text" class="form-control" id="cidade" placeholder="Cidade">
      </div>

      <div class="form-group col-md-6">
        <label for="estado">Estado</label>
        <input type="text" class="form-control" id="estado" placeholder="Estado">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="pais">País</label>
        <input type="text" class="form-control" id="pais" placeholder="País">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label for="email">E-mail</label>
        <input required type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="E-mail">
      </div>

      <div class="form-group col-md-6 ">
        <label for="senha">Senha</label>
        <input required type="password" class="form-control" id="senha" placeholder="Senha">
      </div>
    </div>

    <div class="row col-md-6 offset-md-3">
      <button class="btn btn-outline-secondary mr-5"><a href="index.php" >Cancelar</a></button>
      <button id="btnSalvar" type="submit" class="btn btn-outline-info float-right mr-5">Salvar</button>
    </div>
  </form>
</div>

<script type="text/javascript">
  $('#formCadastrar').submit(function (event) {

    event.preventDefault();

    var dadosCliente = {};

    $('#formCadastrar :input').each(function () {
      dadosCliente[$(this).attr("id")] = $(this).val();
    });

    console.log(dadosCliente);

    $('#btnSalvar').prop("disabled", true);
    $('#btnSalvar').html(
    `<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>`
    );

    $.post('/cadastrarCliente', dadosCliente, function (data) {
      console.log(data);
      if (JSON.parse(data).status == 'ok') {
        alert("Cadastro realizado com sucesso.\nPor favor, efetue o login no sistema.");
        $(location).attr('href', '/');
      }
      else {
          alert(JSON.parse(data).mensagem);
          $('#btnSalvar').prop("disabled", false);
          $('#btnSalvar').html('Salvar');
      }
    });
  });
</script>