<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h1 class="mensagem-topo">Fale Conosco</h1>

<p>Utilize nossos canais para esclarecer suas dúvidas, solicitar informações ou fazer sugestões sobre nossos serviços</p>

<div class="row mx-md-n5 mt-5">
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center">
      <div>
        <i style="font-size:50px;" class="material-icons">local_phone</i>
      </div>
      Telefone
      <p style="font-size:20px;">(11)3003-9299 ou (67)3003-9456</p>
    </div>
  </div>
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center">
      <div><i style="font-size:50px;" class="material-icons">email</i></div>
      Email
      <p style="font-size:20px;">srhotel_fac@gmail.com</p>
    </div>
  </div>
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center">
      <div><i style="font-size:50px;" class="material-icons">where_to_vote</i></div>
      Endereço
      <p style="font-size:20px;">Sr hotel | CNPJ: 06.489.654/0001-05 | Avenida Afonso Pena, 579, 3º andar | Bairro Chácara cachoeira- MS | CEP: 09080-970 | Salas 108-B e 109-B
      </p>
    </div>
  </div>
</div>