<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h1 class="titulo">Sr. Hotel</h1>

<form class="div-input form-inline mt-3" method="POST" action="/buscarHoteis">

    <input type="text" class="form-control mr-sm-2" id="cidade" name="cidade"
      placeholder="Cidade (Ex: Fortaleza)" />
    
    <input type="date" class="form-control mr-sm-2" id="entrada" name="entrada" />
  
    <input type="date" class="form-control mr-sm-2" id="saida" name="saida" />
  
    <button class="btn btn-primary" type="submit">Buscar</button>
</form>

<div class="row mt-5">
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center cards">
      <div>
        <i class="material-icons">apartment</i>
      </div>
      Os Melhores Hotéis
      <p> Encontre o seu hotel ideal e compare preços de vários sites</p>
    </div>
  </div>
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center cards">
      <div><i class="material-icons">attach_money</i></div>
      Os Melhores Preços
      <p>Os hotéis com os melhores preços e condições de pagamento.</p>
    </div>
  </div>
  <div class="col px-md-5">
    <div class="p-3 border bg-light text-center cards">
      <div><i class="material-icons">king_bed</i></div>
      A Maior Comodidade
      <p>Hospede-se tranquilamente, todos os nossos hotéis possuem selo de qualidade de boa hospedagem</p>
    </div>
  </div>
</div>