<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="/imagens/carousel1.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel2.jpg" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="/imagens/carousel3.jpg" class="d-block w-100">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<h1 class="mensagem-topo">Realizando Check-in ? </h1>

<div class="row">
  <div class="col-md-6">
    <div class="border bg-light text-center" style="height: 250px;">
      <p class="font-weight-bold">Sobre Sr.Hotel</p>         

      <p> No que diz respeito ao nosso produto e à nossa organização, estamos na vanguarda da inovação. Estamos curiosos, entusiasmados e motivados pelo desejo de superar as expectativas de nossos usuários.</p>
    </div>
  </div>
  <div class="col-md-6">
    <div class="border bg-light text-center" style="height: 250px;">
      <p class="font-weight-bold">Nossa cultura e valores</p> 

      <p>No Sr.Hotel, não somos nenhum pouco. Somos mais de 1.200 empreendedores, alimentados por uma paixão compartilhada por permanecer à frente do jogo. Somos uma equipe diversificada, curiosa e versátil, de mais de 50 países diferentes, que se reúnem para trabalhar em prol de um objetivo comum.</p>
    </div>
  </div>  
</div>